version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.palantir.baseline:gradle-baseline-java
    versions:
    - 3.66.0
    - 3.68.0
    - 3.68.1
    - 3.69.0
    - 3.73.0
    - 3.73.1
    - 3.74.0
    - 3.75.0
    - 3.75.1
    - 3.76.0
    - 3.78.0
    - 3.79.0
  - dependency-name: com.diffplug.spotless:spotless-plugin-gradle
    versions:
    - 5.10.0
    - 5.10.1
    - 5.10.2
    - 5.11.0
    - 5.11.1
    - 5.12.0
    - 5.12.1
    - 5.9.0
  - dependency-name: com.fasterxml.jackson.module:jackson-module-paranamer
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: nebula.dependency-recommender
    versions:
    - 10.0.0
    - 9.1.1
  - dependency-name: org.datanucleus:datanucleus-api-jdo
    versions:
    - 5.2.5
  - dependency-name: org.datanucleus:datanucleus-rdbms
    versions:
    - 5.2.6
  - dependency-name: org.datanucleus:datanucleus-core
    versions:
    - 5.2.6
  - dependency-name: me.champeau.gradle:jmh-gradle-plugin
    versions:
    - 0.5.2
