name: Check Markdown docs links

on:
  push:
    paths:
      - docs/**
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: 'site/link-checker-config.json'
          use-verbose-mode: yes
